version: '3'
services:
  app:
    image: us-docker.pkg.dev/qwiklabs-gcp-02-f88671d34b9c/george-laravel-demo/laravel-demo:v1
    build:
      context: ./
    volumes:
      - .:/var/www
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=local
